### ISSUE TITLE
sort imports does ignore prettier-ignore statements

### ISSUE THREAD

**Issue by ivanmcgregor** [trivago/prettier-plugin-sort-imports#112]
**Your Environment**
 * **Prettier version**: 2.4.1 / 2.2.1 (both in yarn lock)
 * **node version**: v17.0.1
 * **package manager**: yarn@2
 * **IDE**: Webstorm
 * **prettier-plugin-sort-import: 3.1.1
**Describe the bug**

**To Reproduce**

Add the prettier config and add a new js or ts file. There add one import to the top that does not belong to the top usually and try to make it stay at the top via `// prettier-ignore` ([and variants](https://prettier.io/docs/en/ignore.html)).

**Expected behavior**
When ordering imports I would expect it to be possible to ignore imports that need to be at a certain position (e.g. why-did-you-render wanting to be imported at the top). The prettier-ignore should not be ignored.

**Screenshots, code sample, etc**
```js
// prettier-ignore-start
import "../../scripts/wdyr"; // must be first import!
// prettier-ignore-end

import { ApolloProvider } from "@apollo/client";
import React from "react";
```
turns into 
```
// prettier-ignore-start
// must be first import!
// prettier-ignore-end
import { ApolloProvider } from "@apollo/client";
import React from "react";

import "../../scripts/wdyr";
```

and 
```js
// prettier-ignore
import "../../scripts/wdyr"; // must be first import!

import { ApolloProvider } from "@apollo/client";
import React from "react";
```
turns into
```
// prettier-ignore
// must be first import!
import { ApolloProvider } from "@apollo/client";
import React from "react";

import "../../scripts/wdyr";
```

As can be seen, the first import does not stay the first import.

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**
```js
module.exports = {
  importOrder: ["^@/(.*)$", "^[./]"],
  importOrderSeparation: true,
};
```

**Error log**
No log.

**Contribute to @trivago/prettier-plugin-sort-imports**

- [x] I'm willing to fix this bug 🥇 (if provided a bit of guidance where to look)

**Comment by blutorange** [comment]
@ivanmcgregor The first import seems to be a side effect import, for which I made an isue here #110 and a PR here #111

I had the same issue with test files, these imports really should not be reordered, as their only purpose is side effects. I'd also advocate making not sorting side effect imports the default, without requiring comments.

This should solve the case you mentioned, but I guess we could discuss here whether it's still necessary to support turning off the sorting for arbitrary imports via comments.

While making the changes for #111 I also had the idea that we could use the same mechanism for this feature -- treat import declarations with an ignore comment the same as a side effect import and do not reorder them.

That said, if this does get implemented, one question that comes to my mind is: how should imports before and after the ignore section be treated?

```javascript
import z2 from "z2";
import z1 from "z1";
// prettier-ignore-start
import y from "y";
// prettier-ignore-end
import x2 from "x2";
import x1 from "x1";
```

Obviously x1 should come before x2 and z1 before z2, but should the x's be moved before the z's (and if so, should they now be before or after the ignore section)?

If we used the same mechanism as in my PR, the z's would stay above the ignore section and the x's below it, which imo would make sense and be easy to understand

**Comment by ivanmcgregor** [comment]
Seems that I missed that when scanning for similar tickets to my bug, thanks for mentioning it. Although I would agree that your described behavior matches my expected behavior and would alleviate my issue here, I feel that a plugin should not break with default behavior of the parent. On the other hand I do not know how well prettier passes along things like those ignore statements so that they do not have to be reimplemented.

You did raise a valid point and after checking out your issue and PR I guess you would side with you on treating the ignore as a separate section. 👍

**Comment by blutorange** [comment]
Most cases I hope should be solved by not reordering side effect imports :) But yes, I agree, prettier plugins should follow prettier conventions, if possible. 

Speaking of conventions, though, when I [read the docs](https://prettier.io/docs/en/ignore.html), there's two options for turning of formatting (I've only recently started using prettier, so I might be wrong about this):

* use a `//prettier-ignore`  comment to turn of formatting for a syntax node. This doesn't really apply here because reordering imports is not formatting a single node, it is a global modification over multiple nodes.
* use a ranged ignore comment `<!-- prettier-ignore-start -->` and `<!-- prettier-ignore-end -->`. But [in the docs](https://prettier.io/docs/en/ignore.html#range-ignore) they make this restriction: `This type of ignore is only allowed to be used in top-level and aimed to disable formatting for auto-generated content, e.g. all-contributors, markdown-toc, etc.` Which I'm not quite sure what to make of, it reads a bit like a header at the top of a file that prettier just cuts of before applying the formatter. There's [also this issue](https://github.com/prettier/prettier/issues/5287) about ranged ignores for JS that's still open. On the online playground, [ranged comments also do not seem to be working for JavaScript](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwA5tXHLlM-gLz4A6IABalyggDT5W7eHV74A5IKq06ghZIDOOEghjzUAQxKa4k6AFkI6UwHkAbnGriAvgEp8wflHz4A9H74AA5sMLhOALQ4zFA0cBGaMIbUMN6+kFCJ+AAeBhAQDL4AnPhuANxp-oEhHOHUUTFxEQhqUJUBwaF1DbFslRlZuXyo+YX4JaUVUC4g4iAQQbjQmsigydQQAO4ACskIKyjGm4YAnitzAEbUhmAA1hwAyoYAtnAAMjhQcMhGJmYgVxu9xgDyCN0+zGQMGo6H+cGeFzgdDoSLehi46EMzDgADEaM9DGEIcgQIZ0DAILNhDBniQKEIcPBNGCwHAHvtGTh7IyTiSwJpziBPqYUttrswCT9jKY5gArTTZB4Q3QARXQEHgUr+czB1BFJJgJyCcE0YGoOEWVJCnxgFBwdBgQmQAA4AAw6jamCjXIIkmoixxUgCO6vgYoWB1JmgiXyRSKpbBDODYYqxkqQvxlIFMzxwUJh-20XFVoe+Gel-ySFztDqdSAATHNoYYdBCAMIQZ7pkAmgCsVJscAAKoYLgdM-97LCAJJQFGwB5mi0wACCc4eht0WtMLhcQA)

Also, looking at the plugin interface, prettier does not seems to pass any info about ignore ranges to plugins. So this would have to be implemented from scratch. Which wouldn't be terribly hard, since comments are already processed by this plugin to keep them at the correct import declaration. But it's something to consider when deciding whether it should be implemented.

But yeah, one major difference between reordering imports and "normal" formatting is that reordering imports is a global modifications over multiple nodes, so treating it as a section might be the best solution if this gets implemented.

**Comment by denik1981** [comment]
Not solved yet? 

I'm running prettier-sort-imports in conjunction with playwright which uses a global test file aimed to determine the order of tests The order is defined by the order in how the side-effects imports for each test are arranged in this file. I'm not able to ignore the plugin nor by inline comments neither on the `prettierignore` file.

**Comment by blutorange** [comment]
@denik1981 If it's only the side-effect imports for which you want to preserve the order, you could try this fork https://www.npmjs.com/package/@ianvs/prettier-plugin-sort-imports which includes the PR I made that was not accepted. (Seeing that many people seem to be affected, any chance that PR can get merged?)

Also, based on how that PR handles side effects, it would be possible to implement ignore comments by marking imports with such a comment as a "side-effect import".

**Comment by denik1981** [comment]
@blutorange Yes, I have the thread on the PR. Shame this is not considered a bug because it is indeed a critical one.
Thanks for your contribution.

**Comment by braianj** [comment]
@ayusharma Do you have an estimate of when they are going to fix something as important as this?

**Comment by Morriz** [comment]
yeah, too bad we can't use this plugin without this fix ;(

**Comment by denik1981** [comment]
> Just use ESLint with sorting plugin

I finally ended up using that, and I encourage people to use it instead. 
This project seems to be unmaintained.

**Comment by Dezzymei** [comment]
Is there a fix for this that I am missing?

**Comment by ahmafi** [comment]
This is also stopping me from using this plugin.

**Comment by Iuriy-Budnikov** [comment]
I have the same issue with ordering in tests

**Comment by felixcatto** [comment]
Any progress? :cry:

**Comment by gentrithalili1** [comment]
+1

**Comment by lianghx-319** [comment]
any update?

**Comment by Zehelein** [comment]
I found a "decently nice" workaround by adding `// eslint-disable-next-line prettier/prettier` to the **next** line:

For example, defining the dotenv paths to search for ENV variables must run before the Config is initialized:

```
import dotenv from 'dotenv';
dotenv.config({ path: path.join(__dirname, '.env') });
// eslint-disable-next-line prettier/prettier
dotenv.config({ path: path.join(__dirname, '../.env'), override: true });
// eslint-disable-next-line prettier/prettier
import { Config } from './config';
```

Not the nicest solution but one that works (for me).

**Comment by a613** [comment]
The best solution I found was to disable ordering in the entire file. This works for me since I only have 1 file that needs the exception.

https://github.com/trivago/prettier-plugin-sort-imports/blob/main/docs/TROUBLESHOOTING.md#q-how-can-i-prevent-the-plugin-from-reordering-specific-import-statements

> adding the following comment at the top of your file: `// sort-imports-ignore`

**Comment by AntonioLuisME** [comment]
> The best solution I found was to disable ordering in the entire file. This works for me since I only have 1 file that needs the exception.
> 
> https://github.com/trivago/prettier-plugin-sort-imports/blob/main/docs/TROUBLESHOOTING.md#q-how-can-i-prevent-the-plugin-from-reordering-specific-import-statements
> 
> > adding the following comment at the top of your file: `// sort-imports-ignore`

This doesn't work for me.

**Comment by ms-dosx86** [comment]
> The best solution I found was to disable ordering in the entire file. This works for me since I only have 1 file that needs the exception.
> 
> https://github.com/trivago/prettier-plugin-sort-imports/blob/main/docs/TROUBLESHOOTING.md#q-how-can-i-prevent-the-plugin-from-reordering-specific-import-statements
> 
> > adding the following comment at the top of your file: `// sort-imports-ignore`

Worked for me, thanks!

**Comment by niko7o** [comment]
> > The best solution I found was to disable ordering in the entire file. This works for me since I only have 1 file that needs the exception.
> > https://github.com/trivago/prettier-plugin-sort-imports/blob/main/docs/TROUBLESHOOTING.md#q-how-can-i-prevent-the-plugin-from-reordering-specific-import-statements
> > > adding the following comment at the top of your file: `// sort-imports-ignore`
> 
> This doesn't work for me.

It has to be set at the top of the file as first line, that got it to work for me - in case that helps someone else!
