### ISSUE TITLE
SyntaxError: This experimental syntax requires enabling the parser plugin: 'classProperties' (118:33)

### ISSUE THREAD

**Issue by jmls** [trivago/prettier-plugin-sort-imports#22]
when I install this plugin, vscode and prettier stop formatting with the above error

I'm using vscode 1.52.1, with typescript 4.1.2

the stack trace is this

```
at Object._raise (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:748:17)
	at Object.raiseWithData (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:741:17)
	at Object.expectPlugin (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:9106:18)
	at Object.parseClassProperty (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12722:12)
	at Object.parseClassProperty (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:6968:18)
	at Object.pushClassProperty (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12690:30)
	at Object.parseClassMemberWithIsStatic (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12595:14)
	at Object.parseClassMemberWithIsStatic (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:6856:11)
	at Object.parseClassMember (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12532:10)
	at callParseClassMember (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:6820:13)
	at Object.parseClassMember (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:6826:7)
	at /workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12477:14
	at Object.withTopicForbiddingContext (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:11516:14)
	at Object.parseClassBody (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12454:10)
	at Object.parseClass (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12427:22)
	at Object.parseStatementContent (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:11718:21)
	at Object.parseStatementContent (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:6806:18)
	at Object.parseStatement (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:11676:17)
	at Object.parseExportDeclaration (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12892:17)
	at Object.parseExportDeclaration (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:6927:27)
	at Object.maybeParseExportDeclaration (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12848:31)
	at Object.parseExport (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12786:29)
	at Object.parseExport (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:6769:20)
	at Object.parseStatementContent (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:11782:27)
	at Object.parseStatementContent (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:6806:18)
	at Object.parseStatement (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:11676:17)
	at Object.parseBlockOrModuleBlockBody (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12258:25)
	at Object.parseBlockBody (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:12249:10)
	at Object.parseTopLevel (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:11607:10)
	at Object.parse (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:13415:10)
	at Object.parse (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/node_modules/@babel/parser/lib/index.js:13468:38)
	at Object.preprocessor [as preprocess] (/workspace/node_modules/@trivago/prettier-plugin-sort-imports/lib/src/preprocessor.js:21:24)```

**Comment by jennmueng** [comment]
I have this issue as well, I do have `'@babel/plugin-proposal-class-properties'` in my `babel.config.js` and works elsewhere just fine.

**Comment by levenleven** [comment]
Same here, seems like once `prettier-plugin-sort-imports` installed prettier can't pick the right parser for file

**Comment by levenleven** [comment]
The problem is that `loadPartialConfig()` doesn't return options in format expected by parser.
https://github.com/trivago/prettier-plugin-sort-imports/blob/master/src/preprocessor.ts#L17-L20

**Comment by robinzachmann** [comment]
I'm having the same issue. Does someone know a workaround for this? I have just a single class that is causing the stated error.

**Comment by jennmueng** [comment]
> I'm having the same issue. Does someone know a workaround for this? I have just a single class that is causing the stated error.

You can add [one of these](https://babeljs.io/docs/en/babel-parser#plugins) to this array here: https://github.com/trivago/prettier-plugin-sort-imports/blob/e212c0524f0177c03420d59ede41d70c157a07bb/src/preprocessor.ts#L15

For example, `classProperties` would fix this issue.

**Comment by levenleven** [comment]
This is how prettier defines the plugins list https://github.com/prettier/prettier/blob/master/src/language-js/parser-babel.js

**Comment by gregkonush** [comment]
having the same issue with `SyntaxError: This experimental syntax requires enabling the parser plugin: 'classProperties' (28:19)`

**Comment by rek** [comment]
> > I'm having the same issue. Does someone know a workaround for this? I have just a single class that is causing the stated error.
> 
> @robinzachmann You can add [one of these](https://babeljs.io/docs/en/babel-parser#plugins) to this array here:
> 
> https://github.com/trivago/prettier-plugin-sort-imports/blob/e212c0524f0177c03420d59ede41d70c157a07bb/src/preprocessor.ts#L15
> 
> For example, `classProperties` would fix this issue.

`classProperties` worked for me, but then I ran into `Unexpected token` when it came across a typescript generic

**Comment by byara** [comment]
Thanks everyone for bringing up this issue. With the release of [v2.0.1](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v2.0.1), this should be fixed. 
Either prettier will figure out the syntax correctly, or you can use `experimentalBabelParserPluginsList` to pass the correct parser name.

If there was still problems, you can of course re-open this issue.

**Comment by ziaulrehman40** [comment]
Am I the only one still getting this error on latest verions?

**Comment by bogdibota** [comment]
Adding this
```
  "experimentalBabelParserPluginsList": [
    "jsx",
    "typescript"
  ]
```
to `.prettierrc` solved the issue for me

**Comment by dweemx** [comment]
Adding this,
```
module.exports = {
  importOrderParserPlugins: ["classProperties", "typescript", "jsx"],
};

```
to `.prettier.config.js` solved the issue for me

Version of `@trivago/prettier-plugin-sort-imports` is: `^3.0.0`

**Comment by nirajhx** [comment]
Still facing the same issue.
Using prettier `2.5.1` & `3.1.1` for `prettier-plugin-sort-imports`, when I run the prettier check, it prints:
```
[warn] Ignored unknown option { experimentalBabelParserPluginsList: ["classProperties", "jsx", "typescript"] }.
```
Its a NestJS + TS codebase

**Comment by MoSattler** [comment]
Same problem here as @nirajhx

**Comment by SalahAdDin** [comment]
> Adding this,
> 
> ```
> module.exports = {
>   importOrderParserPlugins: ["classProperties", "typescript", "jsx"],
> };
> ```
> 
> to `.prettier.config.js` solved the issue for me
> 
> Version of `@trivago/prettier-plugin-sort-imports` is: `3.0.0`

In my case it used this: `"importOrderParserPlugins": ["importAssertions", "typescript", "jsx"],`.

I was getting this error:
```
["ERROR" - 14:59:14] Error formatting document.
["ERROR" - 14:59:14] This experimental syntax requires enabling the parser plugin: "importAssertions". (3:42)
   1 | import { IUser } from "@domain/user.dto";
   2 | import { rest } from "msw";
   3 | import users from './entities/users.json' assert { type: 'json' };
```

So, thank you very much bro!

**Comment by AcrylicShrimp** [comment]
Ok, I'm using this plugin of version `4.0.0`, and I solved this problem by adding below to `.prettier.config.js`.

```js
"importOrderParserPlugins": ["decorators-legacy", "typescript", "jsx"]
```
